### ISSUE TITLE
Font expansion error

### ISSUE THREAD

**Issue by akbari59** [saurabhg17/SPhdThesis#1]
Dear Saurabh Garg,

Hope you are doing well and thanks for sharing  the latex template for NUS thesis. In short, I want to use the template for my thesis, so I tried to compile the example file. However, I got the following error:

! pdfTeX error (font expansion): auto expansion is only possible with scalablefonts.\AtBegShi@Output ...ipout \box \AtBeginShipoutBox\fi \fi \input

I wonder that do you have any idea about the source of the error?

Cheers,
Mohammad

**Comment by saurabhg17** [comment]
Dear Mohammad,

The most obvious thing that I can notice is that you are using pdftex. SPhdThesis should be compiled with pdflatex.

Regards,
Saurabh
