### ISSUE TITLE
About List of Symbols

### ISSUE THREAD

**Issue by DreamWest** [saurabhg17/SPhdThesis#3]
Dear Saurabh Garg,

I really appreciate your sharing the latex template for NUS thesis. Currently, I am working on my thesis and this template has helped me a lot.

However, I notice that this template does not provide the function of list of symbols. Is there a way to deal with this issue? 

Thanks for your time and best regards,

James

**Comment by saurabhg17** [comment]
Dear James,

You have to manually add list of symbols. You can following the discussion in the link below to add lsit of symbols:
[https://tex.stackexchange.com/questions/348640/how-to-effectively-use-list-of-symbols-for-a-thesis](https://tex.stackexchange.com/questions/348640/how-to-effectively-use-list-of-symbols-for-a-thesis)

~Saurabh
