### ISSUE TITLE
Cyrillic character 

### ISSUE THREAD

**Issue by sevilaybayatli** [saurabhg17/SPhdThesis#5]
hi,
I have to use Cyrillic character in my thesis besides main language is English, which packages support both of them and the latex compile without any error?

could point me ?

Sevilay

**Comment by saurabhg17** [comment]
Hi Sevilay,

You can see this thread for using Cyrillic characters:
[https://tex.stackexchange.com/questions/816/cyrillic-in-latex](https://tex.stackexchange.com/questions/816/cyrillic-in-latex).

~Saurabh
