### ISSUE TITLE
Changing Bibliography style

### ISSUE THREAD

**Issue by sevilaybayatli** [saurabhg17/SPhdThesis#6]
Hi,
I have tried to change the bibliography style but after use several format  by using this package \usepackage{natbib} I couldn't change it.

The format I want look like:

Text:
 Tatar-Bashkir (Tyers et al., 2012b),Crimean Tatar-Turkish and English-Kazakh (Sundetova
et al., 2015) MT systems

Reference:
Tyers, F. M., Washington, J. N., Salimzyanov, I., and Batalov, R. (2012b). A prototype machine
translation system for Tatar and Bashkir based on free/open-source components. In First Workshop
on Language Resources and Technologies for Turkic Languages, page 11.

could you point me how to obtain that format?

**Comment by saurabhg17** [comment]
Hi,

 

It is because SPhdThesis.cls sets the bibliographystyle to alpha at line 231. You need to uncomment it first. 

 

Regards,

Saurabh

**Comment by sevilaybayatli** [comment]
I don't know which line you mean in which file the whole information I have
in the main.txt these

\documentclass{SPhdThesis}

%\usepackage[utf8]{inputenc}
%\usepackage[russian]{babel}

\usepackage{cmap} % поиск в PDF
\usepackage[T2A]{fontenc} % кодировка
\usepackage[utf8]{inputenc} % кодировка исходного текста
\usepackage[russian,english]{babel}
%\newenvironment{abbreviations}
\usepackage{amsmath}

% PDF and title properties.
\SgSetTitle{A Robust Mesh-based Surface Integration Algorithm}
\SgSetAuthor{Saurabh Garg}
\SgSetAuthorDegrees{List your previous degrees here}
\SgSetYear{2013}
\SgSetDegree{Doctor of Philosophy}
\SgSetDepartment{Department of Computer Science}
\SgSetUniversity{National University of Singapore}
\SgSetDeclarationDate{June 2013}
%\usepackage{natbib}
%\bibliographystyle{humannat}

% The document.
\begin{document}
\begin{frontmatter}
\SgAddTitle%
\SgAddDeclaration%
\input{acknowledgments}%
\input{abstract}%
\SgAddToc%  Table contents.
\SgAddLof%  List of figures.
\SgAddLot%  List of tables.
\SgAddLoa%  List of algorithms.
\end{frontmatter}
    \pagestyle{plain}

\input{chapter1}
\SgIncludeBib{biblio}

    %\usepackage{natbib}

\end{document}

could you tell in which file the line 231?

**Comment by sevilaybayatli** [comment]
I didn't find the line 231 in the thesis.txt file, could you please tell
which file the line 231 exist?

thanks for help in advance,

Sevilay

**Comment by sevilaybayatli** [comment]
I am using overleaf version and I couldnot find the SPhdThesis.cls, please
could you tell me where is it ?

**Comment by sevilaybayatli** [comment]
Hi,

I have downloaded from github but now have another error:

./algorithm.tex:15:
Undefined control sequence.
l.15 ...heta(B^r), \theta(A^l), \theta(A^r), \vect
                                                  {W}^l, \vect{W}^r)$ \; 

please, could you tell me how to fix this error?

**Comment by sevilaybayatli** [comment]
the last problem is solved, now I have different problem and after try different bibliography style still the problem same like that [Zhou et al.(2006)Zhou, Lio, and Li] it gives me between square bracts how to change this ?
 
 [Zhou et al.(2006)Zhou, Lio, and Li] H. Zhou, Y. Lio, and L. Li. Incremental mesh-based
integration of registered range images: Robust to registration error and scanning noise.
In Asian Conference on Computer Vision, pages 958–968, 2006.

**Comment by saurabhg17** [comment]
I don't used OverLeaf so I cannot help you there. What might work is to copy SPhDThesis.cls from Github to the local folder in OverLeaf. Then comment line 231 in the cls file. Finally, you need to add your own bibliographystyle in the main.txt.

**Comment by sevilaybayatli** [comment]
Hi,
how to change the bibliography style, I have trouble to change it, I have been trying more than one way but I failed, can you point me please ?

**Comment by sevilaybayatli** [comment]
the problem  is after I commented the bibliography style in  SPhDThesis.cls and without add any  bibliography style still the same bibliography style working
